// Prints the SQL that loads every seat in src/data/venueLayout.ts into the venue_seats table.
// Run with: npm run seats:sql > supabase/migrations/<next>_venue_seats.sql
import { allSeats } from '../src/data/venueLayout.ts'

const q = (v: string | null) => (v === null ? 'null' : `'${v.replace(/'/g, "''")}'`)

const rows = allSeats.map((s) => `  (${q(s.id)}, ${q(s.floor)}, ${q(s.tableId)}, ${q(s.label)})`)

console.log(`-- Generated by scripts/generate-seat-sql.ts from src/data/venueLayout.ts — do not edit by hand.
-- ${allSeats.length} seats: ${allSeats.filter((s) => s.tableId).length} at tables, ${allSeats.filter((s) => !s.tableId).length} single.
insert into venue_seats (id, floor, table_id, label)
values
${rows.join(',\n')}
on conflict (id) do update set floor = excluded.floor, table_id = excluded.table_id, label = excluded.label;

-- Seats no longer in the layout (only removable while nothing references them)
delete from venue_seats v
where v.id not in (${allSeats.map((s) => q(s.id)).join(', ')})
  and not exists (select 1 from seat_reservations r where r.seat_id = v.id);

-- Every show sells the full house
update shows set capacity = (select count(*) from venue_seats);
alter table shows alter column capacity set default ${allSeats.length};`)
